"""testnet gamification tables

Revision ID: 14ababb98d69
Revises: 75780a782bf2
Create Date: 2026-07-12 10:58:16.438938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '14ababb98d69'
down_revision: Union[str, None] = '75780a782bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_nonces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_nonces_wallet_address'), 'wallet_nonces', ['wallet_address'], unique=True)
    op.create_table('testers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('display_name', sa.String(length=40), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_testers_wallet_address'), 'testers', ['wallet_address'], unique=True)
    op.create_table('point_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tester_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tester_id'], ['testers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_events_created_at'), 'point_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_point_events_tester_id'), 'point_events', ['tester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_point_events_tester_id'), table_name='point_events')
    op.drop_index(op.f('ix_point_events_created_at'), table_name='point_events')
    op.drop_table('point_events')
    op.drop_index(op.f('ix_testers_wallet_address'), table_name='testers')
    op.drop_table('testers')
    op.drop_index(op.f('ix_wallet_nonces_wallet_address'), table_name='wallet_nonces')
    op.drop_table('wallet_nonces')
    # ### end Alembic commands ###
