"""last login and user-reported issues

Revision ID: 19cdebe81026
Revises: a9ffdd5adea4
Create Date: 2026-07-12 16:17:11.131149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '19cdebe81026'
down_revision: Union[str, None] = 'a9ffdd5adea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bug_reports', sa.Column('reporter_user_id', sa.Uuid(), nullable=True))
    op.alter_column('bug_reports', 'tester_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_bug_reports_reporter_user_id'), 'bug_reports', ['reporter_user_id'], unique=False)
    op.create_foreign_key(None, 'bug_reports', 'users', ['reporter_user_id'], ['id'])
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_constraint(None, 'bug_reports', type_='foreignkey')
    op.drop_index(op.f('ix_bug_reports_reporter_user_id'), table_name='bug_reports')
    op.alter_column('bug_reports', 'tester_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('bug_reports', 'reporter_user_id')
    # ### end Alembic commands ###
