"""memory prompts

Adds the monthly Memory Request machinery:
- memory_prompts: the once-per-(user, family, calendar month) throttle table
  (mirrors fund_nudges) — unique (user_id, family_id, period), index on
  family_id.
- Two NotificationPreference columns (email/push_memory_request), both default
  true. They carry a server_default so existing preference rows get the product
  default without a data migration (mirrors b8f2c1a9d4e7).

Revision ID: 481888380a06
Revises: b8f2c1a9d4e7
Create Date: 2026-07-21 09:21:58.322951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '481888380a06'
down_revision: Union[str, None] = 'b8f2c1a9d4e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_prompts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'family_id', 'period', name='uq_memory_prompts_user_family_period')
    )
    op.create_index(op.f('ix_memory_prompts_family_id'), 'memory_prompts', ['family_id'], unique=False)
    op.create_index(op.f('ix_memory_prompts_user_id'), 'memory_prompts', ['user_id'], unique=False)
    # server_default so existing preference rows get the product default (true)
    # without a data migration — same style as b8f2c1a9d4e7.
    op.add_column(
        'notification_preferences',
        sa.Column(
            'email_memory_request', sa.Boolean(), nullable=False,
            server_default=sa.text('true'),
        ),
    )
    op.add_column(
        'notification_preferences',
        sa.Column(
            'push_memory_request', sa.Boolean(), nullable=False,
            server_default=sa.text('true'),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_preferences', 'push_memory_request')
    op.drop_column('notification_preferences', 'email_memory_request')
    op.drop_index(op.f('ix_memory_prompts_user_id'), table_name='memory_prompts')
    op.drop_index(op.f('ix_memory_prompts_family_id'), table_name='memory_prompts')
    op.drop_table('memory_prompts')
    # ### end Alembic commands ###
