"""time capsules and legacy archive

Revision ID: 68a0bfedb8be
Revises: a61bf9b1a9ff
Create Date: 2026-07-10 22:11:55.955332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '68a0bfedb8be'
down_revision: Union[str, None] = 'a61bf9b1a9ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legacy_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('story', 'recipe', 'document', 'photo', 'wisdom', name='legacytype', native_enum=False, length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('media_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['media_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legacy_items_family_id'), 'legacy_items', ['family_id'], unique=False)
    op.create_table('time_capsules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('letter', 'audio', 'video', name='capsuletype', native_enum=False, length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('media_id', sa.Uuid(), nullable=True),
    sa.Column('release_condition', sa.Enum('age', 'date', 'milestone', name='releasecondition', native_enum=False, length=20), nullable=False),
    sa.Column('release_age', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('release_milestone', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('sealed', 'released', name='capsulestatus', native_enum=False, length=20), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['media_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_capsules_child_id'), 'time_capsules', ['child_id'], unique=False)
    op.add_column('media_objects', sa.Column('family_id', sa.Uuid(), nullable=True))
    op.alter_column('media_objects', 'child_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_media_objects_family_id'), 'media_objects', ['family_id'], unique=False)
    op.create_foreign_key(None, 'media_objects', 'families', ['family_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media_objects', type_='foreignkey')
    op.drop_index(op.f('ix_media_objects_family_id'), table_name='media_objects')
    op.alter_column('media_objects', 'child_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('media_objects', 'family_id')
    op.drop_index(op.f('ix_time_capsules_child_id'), table_name='time_capsules')
    op.drop_table('time_capsules')
    op.drop_index(op.f('ix_legacy_items_family_id'), table_name='legacy_items')
    op.drop_table('legacy_items')
    # ### end Alembic commands ###
