"""testnet bug reports

Revision ID: 6b612405961d
Revises: 14ababb98d69
Create Date: 2026-07-12 12:05:09.556555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6b612405961d'
down_revision: Union[str, None] = '14ababb98d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tester_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('points_awarded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tester_id'], ['testers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bug_reports_tester_id'), 'bug_reports', ['tester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bug_reports_tester_id'), table_name='bug_reports')
    op.drop_table('bug_reports')
    # ### end Alembic commands ###
