"""family video call + member avatars

Revision ID: 94e8122e469d
Revises: fe030d128586
Create Date: 2026-07-13 07:28:11.881198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '94e8122e469d'
down_revision: Union[str, None] = 'fe030d128586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('active_family_id', sa.Uuid(), nullable=True),
    sa.Column('channel_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('active', 'ended', name='callstatus', native_enum=False, length=20), nullable=False),
    sa.Column('started_by', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_family_id', name='uq_one_active_call_per_family'),
    sa.UniqueConstraint('channel_name')
    )
    op.create_index(op.f('ix_family_calls_family_id'), 'family_calls', ['family_id'], unique=False)
    op.create_table('planned_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('set_by', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['set_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planned_calls_family_id'), 'planned_calls', ['family_id'], unique=True)
    op.create_table('call_child_presence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('marked_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['family_calls.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 'child_id')
    )
    op.create_index(op.f('ix_call_child_presence_call_id'), 'call_child_presence', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_child_presence_child_id'), 'call_child_presence', ['child_id'], unique=False)
    op.create_table('call_participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('agora_uid', sa.BigInteger(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['family_calls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 'agora_uid'),
    sa.UniqueConstraint('call_id', 'user_id')
    )
    op.create_index(op.f('ix_call_participants_call_id'), 'call_participants', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_participants_user_id'), 'call_participants', ['user_id'], unique=False)
    op.add_column('media_objects', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_media_objects_user_id'), 'media_objects', ['user_id'], unique=False)
    op.create_foreign_key(None, 'media_objects', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('avatar_media_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'users', 'media_objects', ['avatar_media_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'avatar_media_id')
    op.drop_constraint(None, 'media_objects', type_='foreignkey')
    op.drop_index(op.f('ix_media_objects_user_id'), table_name='media_objects')
    op.drop_column('media_objects', 'user_id')
    op.drop_index(op.f('ix_call_participants_user_id'), table_name='call_participants')
    op.drop_index(op.f('ix_call_participants_call_id'), table_name='call_participants')
    op.drop_table('call_participants')
    op.drop_index(op.f('ix_call_child_presence_child_id'), table_name='call_child_presence')
    op.drop_index(op.f('ix_call_child_presence_call_id'), table_name='call_child_presence')
    op.drop_table('call_child_presence')
    op.drop_index(op.f('ix_planned_calls_family_id'), table_name='planned_calls')
    op.drop_table('planned_calls')
    op.drop_index(op.f('ix_family_calls_family_id'), table_name='family_calls')
    op.drop_table('family_calls')
    # ### end Alembic commands ###
