"""fund account stripe connect

Revision ID: a05c08f146b0
Revises: 94e8122e469d
Create Date: 2026-07-14 14:00:17.400153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a05c08f146b0'
down_revision: Union[str, None] = '94e8122e469d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_accounts', sa.Column('stripe_account_id', sa.String(length=255), nullable=True))
    op.add_column('fund_accounts', sa.Column('account_status', sa.Enum('none', 'onboarding', 'active', 'restricted', name='fundaccountstatus', native_enum=False, length=20), nullable=False, server_default='none'))
    op.add_column('fund_accounts', sa.Column('setup_by', sa.Uuid(), nullable=True))
    op.add_column('fund_accounts', sa.Column('charges_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('fund_accounts', sa.Column('payouts_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('fund_accounts', sa.Column('requirements_due', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('fund_accounts', sa.Column('onboarding_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fund_accounts', sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'fund_accounts', ['stripe_account_id'])
    op.create_foreign_key(None, 'fund_accounts', 'users', ['setup_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fund_accounts', type_='foreignkey')
    op.drop_constraint(None, 'fund_accounts', type_='unique')
    op.drop_column('fund_accounts', 'activated_at')
    op.drop_column('fund_accounts', 'onboarding_started_at')
    op.drop_column('fund_accounts', 'requirements_due')
    op.drop_column('fund_accounts', 'payouts_enabled')
    op.drop_column('fund_accounts', 'charges_enabled')
    op.drop_column('fund_accounts', 'setup_by')
    op.drop_column('fund_accounts', 'account_status')
    op.drop_column('fund_accounts', 'stripe_account_id')
    # ### end Alembic commands ###
