"""achievement economy and fund ledger

Revision ID: a61bf9b1a9ff
Revises: df2d0a6936ba
Create Date: 2026-07-10 17:06:34.172779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a61bf9b1a9ff'
down_revision: Union[str, None] = 'df2d0a6936ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id')
    )
    op.create_table('goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reward_type', sa.Enum('cash', 'fund_contribution', 'badge', 'privilege', name='rewardtype', native_enum=False, length=20), nullable=False),
    sa.Column('reward_amount_cents', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'archived', name='goalstatus', native_enum=False, length=20), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_child_id'), 'goals', ['child_id'], unique=False)
    op.create_table('badges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.Column('source_goal_id', sa.Uuid(), nullable=True),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['source_goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badges_child_id'), 'badges', ['child_id'], unique=False)
    op.create_table('contributions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('contributor_user_id', sa.Uuid(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fee_cents', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('media_id', sa.Uuid(), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'refunded', name='contributionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('trigger_feed_event_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['contributor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['media_objects.id'], ),
    sa.ForeignKeyConstraint(['trigger_feed_event_id'], ['feed_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contributions_child_id'), 'contributions', ['child_id'], unique=False)
    op.create_table('goal_completions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_by', sa.Uuid(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id')
    )
    op.create_table('fund_ledger_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('entry_type', sa.Enum('contribution', 'goal_reward', 'adjustment', name='ledgerentrytype', native_enum=False, length=20), nullable=False),
    sa.Column('source_contribution_id', sa.Uuid(), nullable=True),
    sa.Column('anchor_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['fund_accounts.id'], ),
    sa.ForeignKeyConstraint(['source_contribution_id'], ['contributions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_contribution_id')
    )
    op.create_index(op.f('ix_fund_ledger_entries_account_id'), 'fund_ledger_entries', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fund_ledger_entries_account_id'), table_name='fund_ledger_entries')
    op.drop_table('fund_ledger_entries')
    op.drop_table('goal_completions')
    op.drop_index(op.f('ix_contributions_child_id'), table_name='contributions')
    op.drop_table('contributions')
    op.drop_index(op.f('ix_badges_child_id'), table_name='badges')
    op.drop_table('badges')
    op.drop_index(op.f('ix_goals_child_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_table('fund_accounts')
    # ### end Alembic commands ###
