"""user disabled flag

Revision ID: a9ffdd5adea4
Revises: f556d1cfaefe
Create Date: 2026-07-12 15:54:35.908513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a9ffdd5adea4'
down_revision: Union[str, None] = 'f556d1cfaefe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'disabled')
    # ### end Alembic commands ###
