"""family max upload mb

Revision ID: add7ac7c4a15
Revises: 19cdebe81026
Create Date: 2026-07-12 16:55:00.689578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'add7ac7c4a15'
down_revision: Union[str, None] = '19cdebe81026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('families', sa.Column('max_upload_mb', sa.Integer(), nullable=False, server_default='10'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('families', 'max_upload_mb')
    # ### end Alembic commands ###
