"""tester avatars and x auth

Revision ID: ce9d0a0430d3
Revises: 6b612405961d
Create Date: 2026-07-12 12:37:35.668079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ce9d0a0430d3'
down_revision: Union[str, None] = '6b612405961d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('x_auth_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tester_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('code_verifier', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tester_id'], ['testers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_x_auth_states_state'), 'x_auth_states', ['state'], unique=True)
    op.create_index(op.f('ix_x_auth_states_tester_id'), 'x_auth_states', ['tester_id'], unique=False)
    op.add_column('testers', sa.Column('x_user_id', sa.String(length=40), nullable=True))
    op.add_column('testers', sa.Column('x_username', sa.String(length=50), nullable=True))
    op.add_column('testers', sa.Column('x_avatar_url', sa.String(length=500), nullable=True))
    op.create_unique_constraint(None, 'testers', ['x_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testers', type_='unique')
    op.drop_column('testers', 'x_avatar_url')
    op.drop_column('testers', 'x_username')
    op.drop_column('testers', 'x_user_id')
    op.drop_index(op.f('ix_x_auth_states_tester_id'), table_name='x_auth_states')
    op.drop_index(op.f('ix_x_auth_states_state'), table_name='x_auth_states')
    op.drop_table('x_auth_states')
    # ### end Alembic commands ###
