"""vault feed and media

Revision ID: df2d0a6936ba
Revises: c37b0d51f312
Create Date: 2026-07-10 16:36:49.644997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'df2d0a6936ba'
down_revision: Union[str, None] = 'c37b0d51f312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('milestone', 'achievement', 'contribution', 'memory_added', 'capsule_created', 'member_joined', name='feedeventtype', native_enum=False, length=20), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_events_created_at'), 'feed_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_feed_events_family_id'), 'feed_events', ['family_id'], unique=False)
    op.create_table('media_objects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'uploaded', 'deleted', name='mediastatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_media_objects_child_id'), 'media_objects', ['child_id'], unique=False)
    op.create_table('vault_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('photo', 'video', 'voice', 'message', 'document', 'achievement', name='vaultitemtype', native_enum=False, length=20), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['media_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_items_child_id'), 'vault_items', ['child_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vault_items_child_id'), table_name='vault_items')
    op.drop_table('vault_items')
    op.drop_index(op.f('ix_media_objects_child_id'), table_name='media_objects')
    op.drop_table('media_objects')
    op.drop_index(op.f('ix_feed_events_family_id'), table_name='feed_events')
    op.drop_index(op.f('ix_feed_events_created_at'), table_name='feed_events')
    op.drop_table('feed_events')
    # ### end Alembic commands ###
