"""bug report screenshots

Revision ID: e166d22b6f2d
Revises: ce9d0a0430d3
Create Date: 2026-07-12 14:29:49.897104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e166d22b6f2d'
down_revision: Union[str, None] = 'ce9d0a0430d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bug_reports', sa.Column('media_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'bug_reports', 'media_objects', ['media_id'], ['id'])
    op.add_column('media_objects', sa.Column('tester_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_media_objects_tester_id'), 'media_objects', ['tester_id'], unique=False)
    op.create_foreign_key(None, 'media_objects', 'testers', ['tester_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media_objects', type_='foreignkey')
    op.drop_index(op.f('ix_media_objects_tester_id'), table_name='media_objects')
    op.drop_column('media_objects', 'tester_id')
    op.drop_constraint(None, 'bug_reports', type_='foreignkey')
    op.drop_column('bug_reports', 'media_id')
    # ### end Alembic commands ###
