"""contribution refunded_cents

Revision ID: f556d1cfaefe
Revises: f2c51841d3ba
Create Date: 2026-07-12 15:43:32.190467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f556d1cfaefe'
down_revision: Union[str, None] = 'f2c51841d3ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributions', sa.Column('refunded_cents', sa.BigInteger(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contributions', 'refunded_cents')
    # ### end Alembic commands ###
