"""moments social, supporter role, capsule rules, headshots, notif prefs

Revision ID: fe030d128586
Revises: add7ac7c4a15
Create Date: 2026-07-12 20:15:31.445655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fe030d128586'
down_revision: Union[str, None] = 'add7ac7c4a15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email_new_member', sa.Boolean(), nullable=False),
    sa.Column('email_milestone', sa.Boolean(), nullable=False),
    sa.Column('email_memory', sa.Boolean(), nullable=False),
    sa.Column('email_legacy', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('reactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.Enum('feed_event', 'comment', name='reactiontargettype', native_enum=False, length=20), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type', 'target_id', 'user_id', 'emoji')
    )
    op.create_index(op.f('ix_reactions_target_id'), 'reactions', ['target_id'], unique=False)
    op.create_table('capsule_release_votes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('capsule_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capsule_id'], ['time_capsules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capsule_id', 'user_id')
    )
    op.create_index(op.f('ix_capsule_release_votes_capsule_id'), 'capsule_release_votes', ['capsule_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('feed_event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['feed_event_id'], ['feed_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_comments_feed_event_id'), 'comments', ['feed_event_id'], unique=False)
    op.add_column('children', sa.Column('avatar_media_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'children', 'media_objects', ['avatar_media_id'], ['id'])
    op.add_column('time_capsules', sa.Column('release_goal_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'time_capsules', 'goals', ['release_goal_id'], ['id'])
    op.add_column('vault_items', sa.Column('visible_to_supporters', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vault_items', 'visible_to_supporters')
    op.drop_constraint(None, 'time_capsules', type_='foreignkey')
    op.drop_column('time_capsules', 'release_goal_id')
    op.drop_constraint(None, 'children', type_='foreignkey')
    op.drop_column('children', 'avatar_media_id')
    op.drop_index(op.f('ix_comments_feed_event_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_capsule_release_votes_capsule_id'), table_name='capsule_release_votes')
    op.drop_table('capsule_release_votes')
    op.drop_index(op.f('ix_reactions_target_id'), table_name='reactions')
    op.drop_table('reactions')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
